{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gh-test-chart.serviceAccountName" . }}
  labels:
    {{- include "gh-test-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gh-test-chart.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gh-test-chart.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gh-test-chart.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "gh-test-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
